In [2]:
import pandas as pd

In [4]:
df =pd.read_csv("products-100.csv")

In [5]:
df

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         100 non-null    int64
 1   Name          100 non-null    object
 2   Description   100 non-null    object
 3   Brand         100 non-null    object
 4   Category      100 non-null    object
 5   Price         100 non-null    int64
 6   Currency      100 non-null    object
 7   Stock         100 non-null    int64
 8   EAN           100 non-null    int64
 9   Color         100 non-null    object
 10  Size          100 non-null    object
 11  Availability  100 non-null    object
 12  Internal ID   100 non-null    int64
dtypes: int64(5), object(8)
memory usage: 10.3+ KB

In [9]:
df.head()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Compact Printer Air Advanced Digital,Situation organization these memory much off.,"Garner, Boyle and Flynn",Books & Stationery,265,USD,774,2091465262179,ForestGreen,Large,pre_order,56
1,2,Tablet,Discussion loss politics free one thousand.,Mueller Inc,Shoes & Footwear,502,USD,81,5286196620740,Black,8x10 in,in_stock,29
2,3,Smart Blender Cooker,No situation per.,"Lawson, Keller and Winters",Kitchen Appliances,227,USD,726,1282898648918,SlateGray,XS,in_stock,70
3,4,Advanced Router Rechargeable,For force gas energy six laugh.,Gallagher and Sons,Kitchen Appliances,121,USD,896,3879177514583,PaleGreen,L,discontinued,31
4,5,Portable Mouse Monitor Phone,Feeling back religious however author room sci...,Irwin LLC,Kids' Clothing,1,USD,925,9055773261265,SeaShell,100x200 mm,discontinued,10

In [11]:
df.tail()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
95,96,Router,Investment everything story buy.,Atkinson Inc,Laptops & Computers,375,USD,703,3330396409604,Gainsboro,8x10 in,limited_stock,55
96,97,Fast Thermostat Microphone Scooter,Nature notice themselves news.,Shea Ltd,Beauty & Personal Care,289,USD,727,9265397743935,White,Extra Large,backorder,25
97,98,Eco Heater Toaster Stove Silent Sense,Understand still or summer rule.,West Ltd,Cleaning Supplies,232,USD,998,5505866454530,OldLace,Small,limited_stock,20
98,99,Clean Blender Scale Lite,Final art some push.,"Bell, Gamble and Barrett",Camping & Hiking,241,USD,391,3893594435450,Aquamarine,5x7 in,limited_stock,5
99,100,Smart Lamp,However public major baby.,"Hebert, Hughes and Trujillo",Bedding & Bath,71,USD,518,8264263605712,Brown,Medium,limited_stock,3

In [14]:
df.shape

(100, 13)

In [15]:
df.dtypes

Index            int64
Name            object
Description     object
Brand           object
Category        object
Price            int64
Currency        object
Stock            int64
EAN              int64
Color           object
Size            object
Availability    object
Internal ID      int64
dtype: object

In [16]:
df.size

1300

In [17]:
df.describe()

            Index      Price       Stock           EAN  Internal ID
count  100.000000  100.00000  100.000000  1.000000e+02   100.000000
mean    50.500000  451.19000  545.710000  4.876267e+12    49.340000
std     29.011492  281.60911  266.716863  2.918084e+12    28.078253
min      1.000000    1.00000   10.000000  5.246382e+08     3.000000
25%     25.750000  230.75000  347.500000  2.062323e+12    25.000000
50%     50.500000  407.50000  575.500000  4.875720e+12    48.000000
75%     75.250000  679.00000  749.250000  7.676943e+12    74.500000
max    100.000000  999.00000  998.000000  9.921752e+12    99.000000

In [20]:
df.nunique()

Index           100
Name             99
Description     100
Brand           100
Category         32
Price            96
Currency          1
Stock            96
EAN             100
Color            72
Size             17
Availability      6
Internal ID      66
dtype: int64

In [22]:
df.isnull().sum()

Index           0
Name            0
Description     0
Brand           0
Category        0
Price           0
Currency        0
Stock           0
EAN             0
Color           0
Size            0
Availability    0
Internal ID     0
dtype: int64

In [23]:
df.columns

Index(['Index', 'Name', 'Description', 'Brand', 'Category', 'Price',
       'Currency', 'Stock', 'EAN', 'Color', 'Size', 'Availability',
       'Internal ID'],
      dtype='object')

In [64]:
df.plot